outdir: /users/k1806347/oliverpainfel/Data/OpenSNP/GenoPred/test1
config_file: misc/opensnp/config.yaml
gwas_list: misc/opensnp/gwas_list.txt
score_list: misc/opensnp/score_list.txt
target_list: misc/opensnp/target_list.txt
pgs_methods: ['ptclump','dbslmm','prscs','sbayesr','lassosum','ldpred2','megaprs']
testing: NA
