---
title: "Sequence test"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

***

# Prepare data

```{bash}
cd /users/k1806347/oliverpainfel/Data/1KG/sequence

wget https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000_genomes_project/release/20181203_biallelic_SNV/ALL.chr22.shapeit2_integrated_v1a.GRCh38.20181129.phased.vcf.gz.tbi

wget https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000_genomes_project/release/20181203_biallelic_SNV/ALL.chr22.shapeit2_integrated_v1a.GRCh38.20181129.phased.vcf.gz

ln -s ALL.chr22.shapeit2_integrated_v1a.GRCh38.20181129.phased.vcf.gz.tbi 1kg_seq.chr22.vcf.gz.tbi
ln -s ALL.chr22.shapeit2_integrated_v1a.GRCh38.20181129.phased.vcf.gz 1kg_seq.chr22.vcf.gz

```

```{r}
target_list<-data.frame(
  name='1kg_seq',
  path='/users/k1806347/oliverpainfel/Data/1KG/sequence/1kg_seq',
  type='vcf',
  indiv_report=F
)

write.table(target_list, '/users/k1806347/oliverpainfel/test/1kg_seq/target_list.txt', row.names=F, col.names=T, quote=F)

config<-c(
  'outdir: /users/k1806347/oliverpainfel/Software/MyGit/GenoPred/pipeline/misc/dev/test_data/output',
  'config_file: /users/k1806347/oliverpainfel/test/1kg_seq/config.yaml',
  'target_list: /users/k1806347/oliverpainfel/test/1kg_seq/target_list.txt',
  'testing: chr22'
)

write.table(config, '/users/k1806347/oliverpainfel/test/1kg_seq/config.yaml', row.names=F, col.names=F, quote=F)

```

```{bash}
snakemake --profile slurm --use-conda --configfile=/users/k1806347/oliverpainfel/test/1kg_seq/config.yaml output_all -n
```

