configfile: "config.yaml"

import os
import json
import gzip
import itertools
from snakemake.remote.HTTP import RemoteProvider as HTTPRemoteProvider

HTTP = HTTPRemoteProvider()

wildcard_constraints:
    version="[\d.]+",
    gwas="[^-]+",
    name="[^-]+",
    population="[^-]+",
    method="[^-]+"

include: "rules/dependencies.smk"
include: "rules/target_qc.smk"
include: "rules/pgs_methods.smk"
include: "rules/target_scoring.smk"
include: "rules/report.smk"
