configfile: "config.yaml"

import os
import json
import gzip
import itertools
from snakemake.remote.HTTP import RemoteProvider as HTTPRemoteProvider

HTTP = HTTPRemoteProvider()

# Prevent the user's personal R libraries from being loaded inside conda envs.
# If R_LIBS_USER / R_LIBS / R_HOME are set in the user's shell, R will prefer
# packages from those paths over the conda env's library, which can pull in
# binaries built against a different R version (e.g. data.table without zlib
# support, causing fwrite(".gz") to fail).
shell.prefix("unset R_LIBS_USER R_LIBS R_HOME; ")

wildcard_constraints:
    version="[\d.]+",
    gwas="[^-]+",
    name="[^-]+",
    population="[^-]+",
    method="[^-]+"

include: "rules/dependencies.smk"
include: "rules/target_qc.smk"
include: "rules/pgs_methods.smk"
#include: "rules/magma.smk"
include: "rules/target_scoring.smk"
include: "rules/report.smk"
