outdir: test_data/output/23andMe
config_file: misc/23andMe/config.yaml
gwas_list: misc/23andMe/gwas_list.txt
target_list: misc/23andMe/target_list.txt
score_list: NA
pgs_methods: ['dbslmm']
testing: chr22
