outdir: misc/dev/test_data/output
config_file: misc/dev/test_data/config/config.yaml
resdir: NA
refdir: misc/dev/test_data/ref
gwas_list: misc/dev/test_data/config/gwas_list.txt
target_list: misc/dev/test_data/config/target_list.txt
score_list: misc/dev/test_data/config/score_list.txt
pgs_methods: ['ptclump']
testing: chr22
cores_target_pgs: 1
mem_target_pgs: 2000
