outdir: test_data/output/cross_pop
refdir: misc/dev/test_data/ref
config_file: misc/cross_pop_test/config_cross_pop.yaml
gwas_list: misc/cross_pop_test/gwas_list.txt
target_list: misc/dev/test_data/config/target_list.txt
gwas_groups: misc/cross_pop_test/gwas_groups.txt
pgs_methods: ['ptclump','prscs','prscsx']
testing: chr22
cores_target_pgs: 1
mem_target_pgs: 2000
prscs_phi: ['auto']
