---
title: "Testing cross-populations PGS methods"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(eval = FALSE)
knitr::opts_knit$set(root.dir = '/scratch/prj/oliverpainfel/Software/MyGit/GenoPred/GenoPredPipe')

library(data.table)

```

***

We will test using the mini test data to speed up testing. The configuration files are in ~/oliverpainfel/Software/MyGit/GenoPred/pipeline/misc/cross_pop_test.

```{bash}
snakemake -j1 --use-conda --configfile=misc/cross_pop_test/config_cross_pop.yaml output_all -n
```

***

Test the new set up with OpenSNP data as the target. Initially restrict to chr22 to see if it works as expected.

We need to edit the config file used in the previous run on OpenSNP data.

<details><summary>Show code</summary>

```{r}
setwd('/users/k1806347/oliverpainfel/Software/MyGit/GenoPred/pipeline')

config <- readLines('misc/opensnp/config.yaml')

config[grepl('^testing:', config)]<- 'testing: chr22'
config <- config[!grepl('^score_list:', config)]
config[grepl('^outdir:', config)]<- 'outdir: /users/k1806347/oliverpainfel/Data/OpenSNP/GenoPred/test_cross_pop_1'
config[grepl('^pgs_methods:', config)]<- "pgs_methods: ['ptclump','prscs','prscsx']"
config<-c(config, 'gwas_groups: misc/cross_pop_test/gwas_groups.txt')

write.table(config, 'misc/opensnp/config_cross_pop.yaml', col.names = F, row.names = F, quote = F)

```

```{bash}
snakemake --profile slurm --use-conda --configfile=misc/opensnp/config_cross_pop.yaml output_all
```
