outdir: test_data/output/test1
config_file: example_input/config.multisource.yaml
gwas_list: example_input/gwas_list.multisource.txt
gwas_groups: example_input/gwas_groups.multisource.txt
target_list: example_input/target_list.txt
pgs_methods: ['lassosum']
leopard_methods: ['lassosum']
testing: chr22
cores_prep_pgs: 5
cores_target_pgs: 5
mem_target_pgs: 2000
