# Specify output directory
outdir: test_data/output/test1

# Location of this config file
config_file: example_input/config.yaml

# Specify location of gwas_list file
gwas_list: example_input/gwas_list.txt

# Specify location of target_list file
target_list: example_input/target_list.txt

# Specify location of score_list file
score_list: example_input/score_list.txt

# Specify pgs_methods
pgs_methods: ['ptclump','dbslmm']

# Specify if you want test mode. Set to NA if you don't want test mode
testing: chr22

# Specify number of cores for polygenic scoring methods (ptclump always uses 1)
cores_prep_pgs: 5

# Specify number of cores for target scoring
cores_target_pgs: 5

# Specify memory in megabytes for target scoring
mem_target_pgs: 2000

