# Specify output directory
outdir: test_data/output/test1

# Location of this config file
config_file: example_input/config_example.yaml

# Specify location of gwas_list file
gwas_list: example_input/gwas_list_example.txt

# Specify location of target_list file
target_list: example_input/target_list_example.txt

# Specify location of score_list file
score_list: example_input/score_list_example.txt

# Specify pgs_methods ('ptclump','dbslmm','prscs','sbayesr','lassosum','ldpred2','megaprs')
pgs_methods: ['ptclump','dbslmm']

# Specify if you want test mode. Set to NA if you don't want test mode
testing: chr22
