# MELD Round 7b Section 4 M5 — LDpred2 with panel: MELD_lambda0
# Yengo-2022 height all-ancestry sumstats, AMR-slot hijack pattern.
outdir: /users/k1806347/oliverpainfel/Data/OpenSNP/GenoPred/meld_test_r7bS4_ldpred2_MELD_lambda0
config_file: misc/opensnp/config_meld_r7bS4_ldpred2_MELD_lambda0.yaml
gwas_list: misc/opensnp/gwas_list_r7bS4.txt
target_list: misc/opensnp/target_list.txt
refdir: /users/k1806347/oliverpainfel/Data/OpenSNP/GenoPred/meld_test_r4_refdir_amr
ldpred2_ldref: /users/k1806347/oliverpainfel/Software/MyGit/GenoPred/pipeline/misc/opensnp/private_ldpred2_ldref_MELD_lambda0
pgs_methods: ['ldpred2']
ldpred2_model: ['auto']
ldpred2_inference: F
testing: NA
restrict_to_target_variants: T
target_populations: ['EUR']
