outdir: /users/k1806347/oliverpainfel/Data/OpenSNP/GenoPred/meld_test_r5
config_file: misc/opensnp/config_meld_r5.yaml
gwas_list: misc/opensnp/gwas_list_meld_r5.txt
target_list: misc/opensnp/target_list.txt
refdir: /users/k1806347/oliverpainfel/Data/OpenSNP/GenoPred/meld_test_r4_refdir_amr
quickprs_ldref: /users/k1806347/oliverpainfel/Data/OpenSNP/GenoPred/meld_test_r5_quickprs_ldref
pgs_methods: ['quickprs']
testing: NA
restrict_to_target_variants: T
