outdir: /users/k1806347/oliverpainfel/Data/OpenSNP/GenoPred/test_cross_pop_1
config_file: misc/opensnp/config_cross_pop.yaml
gwas_list: misc/opensnp/gwas_list.txt
target_list: misc/opensnp/target_list.txt
pgs_methods: ['ptclump', 'megaprs','xwing','quickprs']
testing: chr22
gwas_groups: misc/cross_pop_test/gwas_groups.txt
cores_prep_pgs: 10 # Set to 20 when running xwing
quickprs_ldref: /users/k1806347/oliverpainfel/Data/hgdp_1kg/quickprs/hm3