outdir: /users/k1806347/oliverpainfel/Data/OpenSNP/GenoPred/zenodo_10715132.20_ref_pcs
config_file: misc/opensnp/config_zenodo_10715132.20_ref_pcs.yaml
gwas_list: misc/opensnp/gwas_list_zenodo_10715132.txt
target_list: misc/opensnp/target_list_zenodo_10715132.txt
pgs_methods: ['ptclump','quickprs']
pgs_scaling: ['discrete','continuous']
target_populations: ['EUR','TRANS']
restrict_to_target_variants: T
n_ref_pcs: 40
