outdir: /users/k1806347/oliverpainfel/Data/OpenSNP/GenoPred/sparse_test
config_file: misc/opensnp/config_sparse.yaml
score_list: misc/opensnp/score_list.txt
target_list: misc/opensnp/target_list.txt
testing: chr22
