outdir: /users/k1806347/oliverpainfel/Data/OpenSNP/GenoPred/dense_test
refdir: /users/k1806347/oliverpainfel/Data/hgdp_1kg/genopred/ref
config_file: misc/opensnp/config_dense.yaml
score_list: misc/opensnp/score_list.txt
target_list: misc/opensnp/target_list.txt
testing: chr22
