outdir: /users/k1806347/oliverpainfel/Data/OpenSNP/GenoPred/test_ldak
config_file: misc/opensnp/config_ldak.yaml
gwas_list: misc/opensnp/gwas_list.txt
target_list: misc/opensnp/target_list.txt
pgs_scaling: ['continuous', 'discrete']
pgs_methods: ['megaprs','quickprs']
megaprs_ref: quickprs
