outdir: /users/k1806347/oliverpainfel/Data/OpenSNP/GenoPred/test_cross_pop_2
config_file: misc/opensnp/config_cross_pop.yaml
gwas_list: misc/opensnp/gwas_list_cross_pop.txt
target_list: misc/opensnp/target_list.txt
pgs_methods: ['quickprs']
testing: NA
gwas_groups: misc/opensnp/gwas_groups.txt
leopard_methods: ['quickprs']
pgs_scaling: ['continuous', 'discrete']
