outdir: /users/k1806347/oliverpainfel/Data/OpenSNP/GenoPred/meld_test_5x5
config_file: misc/opensnp/config_meld_5x5.yaml
gwas_list: misc/opensnp/gwas_list_meld_5x5.txt
target_list: misc/opensnp/target_list.txt
pgs_methods: ['ptclump','dbslmm','quickprs']
testing: NA
restrict_to_target_variants: T
