outdir: /users/k1806347/oliverpainfel/Data/OpenSNP/GenoPred/test_cross_pop_1
config_file: misc/opensnp/config.yaml
gwas_list: misc/opensnp/gwas_list.txt
target_list: misc/opensnp/target_list.txt
pgs_methods: ['ptclump','prscs','prscsx']
testing: chr22
gwas_groups: misc/cross_pop_test/gwas_groups.txt
