outdir: /users/k1806347/oliverpainfel/Data/OpenSNP/GenoPred/meld_test_r4b
config_file: misc/opensnp/config_meld_r4b.yaml
gwas_list: misc/opensnp/gwas_list_meld_r4b.txt
target_list: misc/opensnp/target_list.txt
refdir: /users/k1806347/oliverpainfel/Data/OpenSNP/GenoPred/meld_test_r4_refdir_afr
pgs_methods: ['dbslmm']
testing: NA
restrict_to_target_variants: T
