# Specify location of gwas_list file
gwas_list: example_input/gwas_list_example.txt

# Specify location of target_list file
target_list: example_input/target_list_example.txt

# Specify location of score_list file
score_list: example_input/score_list_example.txt

# Specify pgs_methods ('ptclump','dbslmm','prscs','sbayesr','lassosum','ldpred2','megaprs')
pgs_methods: ['ptclump','dbslmm','prscs','sbayesr','lassosum','ldpred2','megaprs']

# Specify if you want test mode
testing: chr22
