# Specify location of gwas_list file
gwas_list: gwas_list_example.txt

# Specify location of target_list file
target_list: target_list_example.txt

# Specify location of score_list file
score_list: score_list_example.txt

# Specify pgs_methods
pgs_methods: ['pt_clump','dbslmm']
