name: genopred
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - mamba=1.5.6
  - snakemake-minimal=7.32.3
  - pandas=2.0.3
  - ghostscript=10.02.1
  - pip
  - pip:
      - gdown
