# Specify output directory
outdir: test_data/output/test2

# Location of this config file
config_file: misc/test2/config.yaml

# Specify location of gwas_list file
gwas_list: misc/test2/gwas_list.txt

# Specify location of target_list file
target_list: misc/test2/target_list.txt

# Specify location of score_list file
score_list: misc/test2/score_list.txt

# Specify pgs_methods ('ptclump','dbslmm','prscs','sbayesr','lassosum','ldpred2','megaprs')
pgs_methods: ['ptclump','dbslmm','megaprs']

# Specify if you want test mode. Set to NA if you don't want test mode
testing: chr22
