---
title: Leveraging Global Genetics Resources to Enhance Polygenic Prediction Across Ancestrally Diverse Populations
output: 
  html_document:
    theme: cosmo
    toc: true
    toc_float: true
    css: styles/styles.css
    includes:
      in_header: header.html
      after_body: footer.html

---

***

# Summary

Polygenic scores (PGS) are increasingly used to estimate genetic predisposition to complex traits, but their performance remains inequitable across global populations. This study benchmarks leading polygenic scoring methods for ancestrally diverse populations, evaluating their predictive accuracy and computational efficiency across multiple GWAS datasets.

We evaluated ten complex traits in African (AFR), East Asian (EAS), and European (EUR) populations using publicly available GWAS from the Ugandan Genome Resource, Biobank Japan, UK Biobank, and the Million Veteran Program. We tested both single-source and multi-source PGS methods, including recent advances like SBayesRC, LDpred2, PRS-CSx, TL-PRS, and X-Wing. Multi-source methods leverage GWAS from multiple ancestries to improve prediction.

A key contribution is the application of the LEOPARD method for combining population-specific scores from single-source PGS methods using only summary statistics—avoiding the need for individual-level data. This approach enables practical implementation of multi-source PGS methods even in data-limited settings.

<br/>

# Key Findings

- Multi-source methods consistently outperform single-source models across ancestries, especially for AFR and EAS populations.

- Independently optimised scores, when combined using LEOPARD, outperform jointly optimised methods (e.g. PRS-CSx, X-Wing) with far lower computational cost.

- SBayesRC and LDpred2 were the top-performing single-source methods, with SBayesRC performing best when no individual-level tuning data were available.

- LEOPARD + QuickPRS enables fast, summary-statistic-only tuning of multi-source models (independently or jontly optimised), nearly matching individual-level tuning performance.

- Computational benchmarks show that independently optimised approaches can be completed in under 2 hours per trait with 10 cores—compared to over 30 hours for X-Wing.

<br/>

# Citation

Pain, Oliver. "Leveraging Global Genetics Resources to Enhance Polygenic Prediction Across Ancestrally Diverse Populations." MedRxiv (2025). https://doi.org/10.1101/2025.03.27.25324773

<br/>

# Additional resources

- Code used to conduct the study: [here](CrossPop.html)
- Example applying LEOPARD + QuickPRS to height GWAS from 5 populations and then evaluated in OpenSNP target sample: [here](opensnp_benchmark_crosspop.html)

<br/>

<br/>
