---
title: Genetic analysis of Mirocals trial
output: 
  html_document:
    theme: cosmo
    toc: true
    toc_float: true
    toc_depth: 2
    css: styles/styles.css
    includes:
      in_header: header.html
      after_body: footer.html

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = FALSE)
```

```{css, echo=F}
pre code, pre, code {
  white-space: pre !important;
  overflow-x: scroll !important;
  word-break: keep-all !important;
  word-wrap: initial !important;
}
```

***

# Proposal

The Mirocals trial tested the efficacy of low dose IL-2 for treatment of ALS. The trial showed IL-2 + riluzole treatment provided a significant improvement in survival compared to those only receiving placebo + riluzole. Low dose IL-2 has been shown to increase the number of regulatory T-cells (Tregs).

This trial has collected whole genome sequence data and methylation data (across several time points). This presents an opportunity to identify genetic predictors/biomarkers of response to IL-2 treatment. The sample size of the trial is limited (N drug = 110, N placebo = 110), which means we need to test specific hypotheses and leverage larger external datasets.

***

## Outcome

There are two key outcome variables from the trial, including survival and regulatory T-cell numbers. It seems survival is the more meaningful outcome for patients, but perhaps there are benefits to using T-cell numbers that I am unaware of. If we are using survival, then we should using a cox regression, but if use T cell numbers linear regression.

***

## Polygenic scores (PGS)

List of polygenic scores that might predict response to IL-2:

* ALS risk, survival, age at onset
* Risk of other neurodegenerative diseases
* Interleukin-2 receptor subunit alpha (IL2RA) protein levels
* Regulatory T-cell molecule levels
* Autoimmune disease risk
* Other inflammatory markers (CRP, IL-6, etc.)

I would suggest using SBayesRC as the method to generate the PGS. If GWAS from multiple populations are available we can using SBayesRC-multi.

We could also further stratify the polygenic scores by functional annotations, such as pathway membership. This could be particularly useful, as it may be that only certain pathways are relevant to IL-2 efficacy. For example, ALS risk mediated by inflammatory pathways may be particularly relevant for IL-2 efficacy. 

***

## Methylation scores

We can use previously published EWAS summary statistics to do the same thing. Alternatively, we can use 



