---
title: GenoPred - Index
output: 
  html_document:
    theme: cosmo
    css: styles/styles.css
    includes:
      in_header: header.html
      after_body: footer.html

---

***

# Pipeline

- Overview - <a href="pipeline_overview.html" class="inline_button">Link</a>
- Instructions - <a href="pipeline_readme.html" class="inline_button">Link</a>
- Technical documentation - <a href="pipeline_technical.html" class="inline_button">Link</a>
- Running in an offline environment - <a href="running_offline.html" class="inline_button">Link</a>
- Running on DNAnexus/UKB-RAP - <a href="running_on_dnanexus.html" class="inline_button">Link</a>
- Demonstration using 23anMe data - <a href="pipeline_23andMe.html" class="inline_button">Link</a>
- Computational time/memory benchmark - <a href="pipeline_benchmark.html" class="inline_button">Link</a>
- Benchmark in OpenSNP dataset - <a href="opensnp_benchmark.html" class="inline_button">Link</a>
- Benchmark in UK Biobank dataset - <a href="ukb_benchmark.html" class="inline_button">Link</a>
- Demonstration of multi-source methods to height GWAS and tested in OpenSNP target sample - <a href="opensnp_benchmark_crosspop.html" class="inline_button">Link</a>

***

# Research

- Overview - <a href="research_index.html" class="inline_button">Link</a>
- Comparison of existing polygenic score methodology 
  - Summary - <a href="comparison_of_methods_summary.html" class="inline_button">Link</a>
- Quantifying polygenic signal explained by altered expression
  - Summary - *coming soon...*
  - Code - <a href="Functionally_informed_prediction.html" class="inline_button">Link</a>
- Calibration of polygenic scores to the absolute scale
  - Summary - *coming soon...*
  - Shiny app - <a href="PRS_to_Abs_tool.html" class="inline_button">Link</a>
  - Code - <a href="Absolute_Conversion.html" class="inline_button">Link</a>
  - Conference poster and flash talk - <a href="personal_genome_2021.html" class="inline_button">Link</a>
- Cross-Ancestry Polygenic Prediction
  - Summary - <a href="CrossPop_summary.html" class="inline_button">Link</a>
  - Code - <a href="CrossPop.html" class="inline_button">Link</a>

