---
title: Cross-population evaluation of polygenic scores
output: 
  html_document:
    theme: cosmo
    toc: true
    toc_float: true
    toc_depth: 2
    css: styles/styles.css
    includes:
      in_header: header.html
      after_body: footer.html

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = FALSE)
```

```{css, echo=F}
pre code, pre, code {
  white-space: pre !important;
  overflow-x: scroll !important;
  word-break: keep-all !important;
  word-wrap: initial !important;
}
```

***

This document will explore a shift in the PGS distribution reported in UKB when using the latest anorexia nervosa GWAS. 

I will run this analysis myself using UKB as a target sample.

```{r}
######
# gwas_list
######

dir.create('/users/k1806347/oliverpainfel/Data/ukb/GenoPred/configs/pgs_shift')

gwas_list<-data.frame(
  name='ANOR07',
  path='/scratch/prj/ukbiobank/recovered/Edinburgh_Data/usr/Miryam/project1/sum_stats/ANOR07.gz',
  population='EUR',
  n=NA,
  sampling=NA,
  prevalence=NA,
  mean=0,
  sd=1,
  label=paste0('"Anorexia Nervosa"')
)

write.table(gwas_list, '/users/k1806347/oliverpainfel/Data/ukb/GenoPred/configs/pgs_shift/gwas_list_all.txt', col.names = T, row.names = F, quote = F)

######
# config
######

config<-c(
  "outdir: /users/k1806347/oliverpainfel/Data/ukb/GenoPred/output",
  "config_file: /users/k1806347/oliverpainfel/Data/ukb/GenoPred/configs/pgs_shift/config.yaml",
  "gwas_list: /users/k1806347/oliverpainfel/Data/ukb/GenoPred/configs/pgs_shift/gwas_list_all.txt",
  "target_list: /users/k1806347/oliverpainfel/Data/ukb/GenoPred/configs/basic/target_list.txt",
  "pgs_methods: ['quickprs']",
  "cores_prep_pgs: 1",
  "cores_target_pgs: 1",
  "pgs_scaling: ['continuous', 'discrete']"
)

write.table(config, '/users/k1806347/oliverpainfel/Data/ukb/GenoPred/configs/pgs_shift/config.yaml', col.names = F, row.names = F, quote = F)

```


```{bash}
snakemake \
  --profile slurm \
  --use-conda \
  --configfile=/users/k1806347/oliverpainfel/Data/ukb/GenoPred/configs/pgs_shift/config.yaml \
  /users/k1806347/oliverpainfel/Data/ukb/GenoPred/output/reference/target_checks/ukb/target_pgs-TRANS.done \
  /users/k1806347/oliverpainfel/Data/ukb/GenoPred/output/reference/target_checks/ukb/target_pgs-EUR.done \
  -n
```
